// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/voice-msg-validator/v1/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceMessageDataRq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileSize      int64                  `protobuf:"varint,1,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceMessageDataRq) Reset() {
	*x = VoiceMessageDataRq{}
	mi := &file_proto_voice_msg_validator_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceMessageDataRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceMessageDataRq) ProtoMessage() {}

func (x *VoiceMessageDataRq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_msg_validator_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceMessageDataRq.ProtoReflect.Descriptor instead.
func (*VoiceMessageDataRq) Descriptor() ([]byte, []int) {
	return file_proto_voice_msg_validator_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceMessageDataRq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *VoiceMessageDataRq) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type ValidatedResultRs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValidated   bool                   `protobuf:"varint,1,opt,name=isValidated,proto3" json:"isValidated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatedResultRs) Reset() {
	*x = ValidatedResultRs{}
	mi := &file_proto_voice_msg_validator_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedResultRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedResultRs) ProtoMessage() {}

func (x *ValidatedResultRs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_voice_msg_validator_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedResultRs.ProtoReflect.Descriptor instead.
func (*ValidatedResultRs) Descriptor() ([]byte, []int) {
	return file_proto_voice_msg_validator_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatedResultRs) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

var File_proto_voice_msg_validator_v1_message_proto protoreflect.FileDescriptor

const file_proto_voice_msg_validator_v1_message_proto_rawDesc = "" +
	"\n" +
	"*proto/voice-msg-validator/v1/message.proto\x12\x1amsg.voice.validator.srv.v1\"L\n" +
	"\x12VoiceMessageDataRq\x12\x1a\n" +
	"\bfileSize\x18\x01 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\"5\n" +
	"\x11ValidatedResultRs\x12 \n" +
	"\visValidated\x18\x01 \x01(\bR\visValidatedB<Z:github.com/mefourr/tgdevob/proto/voice-msg-validator/v1/pbb\x06proto3"

var (
	file_proto_voice_msg_validator_v1_message_proto_rawDescOnce sync.Once
	file_proto_voice_msg_validator_v1_message_proto_rawDescData []byte
)

func file_proto_voice_msg_validator_v1_message_proto_rawDescGZIP() []byte {
	file_proto_voice_msg_validator_v1_message_proto_rawDescOnce.Do(func() {
		file_proto_voice_msg_validator_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_voice_msg_validator_v1_message_proto_rawDesc), len(file_proto_voice_msg_validator_v1_message_proto_rawDesc)))
	})
	return file_proto_voice_msg_validator_v1_message_proto_rawDescData
}

var file_proto_voice_msg_validator_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_voice_msg_validator_v1_message_proto_goTypes = []any{
	(*VoiceMessageDataRq)(nil), // 0: msg.voice.validator.srv.v1.VoiceMessageDataRq
	(*ValidatedResultRs)(nil),  // 1: msg.voice.validator.srv.v1.ValidatedResultRs
}
var file_proto_voice_msg_validator_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_voice_msg_validator_v1_message_proto_init() }
func file_proto_voice_msg_validator_v1_message_proto_init() {
	if File_proto_voice_msg_validator_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_voice_msg_validator_v1_message_proto_rawDesc), len(file_proto_voice_msg_validator_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_voice_msg_validator_v1_message_proto_goTypes,
		DependencyIndexes: file_proto_voice_msg_validator_v1_message_proto_depIdxs,
		MessageInfos:      file_proto_voice_msg_validator_v1_message_proto_msgTypes,
	}.Build()
	File_proto_voice_msg_validator_v1_message_proto = out.File
	file_proto_voice_msg_validator_v1_message_proto_goTypes = nil
	file_proto_voice_msg_validator_v1_message_proto_depIdxs = nil
}
