// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/voice-msg-validator/v1/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidateVMLength_ValidateVMLength_FullMethodName = "/msg.voice.validator.srv.v1.ValidateVMLength/ValidateVMLength"
)

// ValidateVMLengthClient is the client API for ValidateVMLength service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidateVMLengthClient interface {
	ValidateVMLength(ctx context.Context, in *VoiceMessageDataRq, opts ...grpc.CallOption) (*ValidatedResultRs, error)
}

type validateVMLengthClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateVMLengthClient(cc grpc.ClientConnInterface) ValidateVMLengthClient {
	return &validateVMLengthClient{cc}
}

func (c *validateVMLengthClient) ValidateVMLength(ctx context.Context, in *VoiceMessageDataRq, opts ...grpc.CallOption) (*ValidatedResultRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatedResultRs)
	err := c.cc.Invoke(ctx, ValidateVMLength_ValidateVMLength_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateVMLengthServer is the server API for ValidateVMLength service.
// All implementations must embed UnimplementedValidateVMLengthServer
// for forward compatibility.
type ValidateVMLengthServer interface {
	ValidateVMLength(context.Context, *VoiceMessageDataRq) (*ValidatedResultRs, error)
	mustEmbedUnimplementedValidateVMLengthServer()
}

// UnimplementedValidateVMLengthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidateVMLengthServer struct{}

func (UnimplementedValidateVMLengthServer) ValidateVMLength(context.Context, *VoiceMessageDataRq) (*ValidatedResultRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateVMLength not implemented")
}
func (UnimplementedValidateVMLengthServer) mustEmbedUnimplementedValidateVMLengthServer() {}
func (UnimplementedValidateVMLengthServer) testEmbeddedByValue()                          {}

// UnsafeValidateVMLengthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateVMLengthServer will
// result in compilation errors.
type UnsafeValidateVMLengthServer interface {
	mustEmbedUnimplementedValidateVMLengthServer()
}

func RegisterValidateVMLengthServer(s grpc.ServiceRegistrar, srv ValidateVMLengthServer) {
	// If the following call pancis, it indicates UnimplementedValidateVMLengthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidateVMLength_ServiceDesc, srv)
}

func _ValidateVMLength_ValidateVMLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoiceMessageDataRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateVMLengthServer).ValidateVMLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidateVMLength_ValidateVMLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateVMLengthServer).ValidateVMLength(ctx, req.(*VoiceMessageDataRq))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidateVMLength_ServiceDesc is the grpc.ServiceDesc for ValidateVMLength service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidateVMLength_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.voice.validator.srv.v1.ValidateVMLength",
	HandlerType: (*ValidateVMLengthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateVMLength",
			Handler:    _ValidateVMLength_ValidateVMLength_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/voice-msg-validator/v1/service.proto",
}
