// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: s3_storage/v1/message.proto

package s3_storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TempRs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Smth          string                 `protobuf:"bytes,1,opt,name=smth,proto3" json:"smth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempRs) Reset() {
	*x = TempRs{}
	mi := &file_s3_storage_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempRs) ProtoMessage() {}

func (x *TempRs) ProtoReflect() protoreflect.Message {
	mi := &file_s3_storage_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempRs.ProtoReflect.Descriptor instead.
func (*TempRs) Descriptor() ([]byte, []int) {
	return file_s3_storage_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *TempRs) GetSmth() string {
	if x != nil {
		return x.Smth
	}
	return ""
}

type TempRq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Smth          string                 `protobuf:"bytes,1,opt,name=smth,proto3" json:"smth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempRq) Reset() {
	*x = TempRq{}
	mi := &file_s3_storage_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempRq) ProtoMessage() {}

func (x *TempRq) ProtoReflect() protoreflect.Message {
	mi := &file_s3_storage_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempRq.ProtoReflect.Descriptor instead.
func (*TempRq) Descriptor() ([]byte, []int) {
	return file_s3_storage_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *TempRq) GetSmth() string {
	if x != nil {
		return x.Smth
	}
	return ""
}

var File_s3_storage_v1_message_proto protoreflect.FileDescriptor

const file_s3_storage_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1bs3_storage/v1/message.proto\x12\x12mefourr.s3.storage\"\x1c\n" +
	"\x06TempRs\x12\x12\n" +
	"\x04smth\x18\x01 \x01(\tR\x04smth\"\x1c\n" +
	"\x06TempRq\x12\x12\n" +
	"\x04smth\x18\x01 \x01(\tR\x04smthB-Z+github.com/mefourr/tgdevob/proto/s3_storageb\x06proto3"

var (
	file_s3_storage_v1_message_proto_rawDescOnce sync.Once
	file_s3_storage_v1_message_proto_rawDescData []byte
)

func file_s3_storage_v1_message_proto_rawDescGZIP() []byte {
	file_s3_storage_v1_message_proto_rawDescOnce.Do(func() {
		file_s3_storage_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s3_storage_v1_message_proto_rawDesc), len(file_s3_storage_v1_message_proto_rawDesc)))
	})
	return file_s3_storage_v1_message_proto_rawDescData
}

var file_s3_storage_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_s3_storage_v1_message_proto_goTypes = []any{
	(*TempRs)(nil), // 0: mefourr.s3.storage.TempRs
	(*TempRq)(nil), // 1: mefourr.s3.storage.TempRq
}
var file_s3_storage_v1_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s3_storage_v1_message_proto_init() }
func file_s3_storage_v1_message_proto_init() {
	if File_s3_storage_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s3_storage_v1_message_proto_rawDesc), len(file_s3_storage_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s3_storage_v1_message_proto_goTypes,
		DependencyIndexes: file_s3_storage_v1_message_proto_depIdxs,
		MessageInfos:      file_s3_storage_v1_message_proto_msgTypes,
	}.Build()
	File_s3_storage_v1_message_proto = out.File
	file_s3_storage_v1_message_proto_goTypes = nil
	file_s3_storage_v1_message_proto_depIdxs = nil
}
