// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: s3_storage/v1/service.proto

package s3_storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	S3Storage_StoreAudio_FullMethodName = "/mefourr.s3.storage.S3Storage/StoreAudio"
)

// S3StorageClient is the client API for S3Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type S3StorageClient interface {
	StoreAudio(ctx context.Context, in *TempRq, opts ...grpc.CallOption) (*TempRs, error)
}

type s3StorageClient struct {
	cc grpc.ClientConnInterface
}

func NewS3StorageClient(cc grpc.ClientConnInterface) S3StorageClient {
	return &s3StorageClient{cc}
}

func (c *s3StorageClient) StoreAudio(ctx context.Context, in *TempRq, opts ...grpc.CallOption) (*TempRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TempRs)
	err := c.cc.Invoke(ctx, S3Storage_StoreAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// S3StorageServer is the server API for S3Storage service.
// All implementations must embed UnimplementedS3StorageServer
// for forward compatibility.
type S3StorageServer interface {
	StoreAudio(context.Context, *TempRq) (*TempRs, error)
	mustEmbedUnimplementedS3StorageServer()
}

// UnimplementedS3StorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedS3StorageServer struct{}

func (UnimplementedS3StorageServer) StoreAudio(context.Context, *TempRq) (*TempRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreAudio not implemented")
}
func (UnimplementedS3StorageServer) mustEmbedUnimplementedS3StorageServer() {}
func (UnimplementedS3StorageServer) testEmbeddedByValue()                   {}

// UnsafeS3StorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to S3StorageServer will
// result in compilation errors.
type UnsafeS3StorageServer interface {
	mustEmbedUnimplementedS3StorageServer()
}

func RegisterS3StorageServer(s grpc.ServiceRegistrar, srv S3StorageServer) {
	// If the following call pancis, it indicates UnimplementedS3StorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&S3Storage_ServiceDesc, srv)
}

func _S3Storage_StoreAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TempRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(S3StorageServer).StoreAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: S3Storage_StoreAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(S3StorageServer).StoreAudio(ctx, req.(*TempRq))
	}
	return interceptor(ctx, in, info, handler)
}

// S3Storage_ServiceDesc is the grpc.ServiceDesc for S3Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var S3Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mefourr.s3.storage.S3Storage",
	HandlerType: (*S3StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreAudio",
			Handler:    _S3Storage_StoreAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "s3_storage/v1/service.proto",
}
