// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: s3_storage/v1/service.proto

package s3_storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_s3_storage_v1_service_proto protoreflect.FileDescriptor

const file_s3_storage_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bs3_storage/v1/service.proto\x12\x12mefourr.s3.storage\x1a\x1bs3_storage/v1/message.proto2Q\n" +
	"\tS3Storage\x12D\n" +
	"\n" +
	"StoreAudio\x12\x1a.mefourr.s3.storage.TempRq\x1a\x1a.mefourr.s3.storage.TempRsB-Z+github.com/mefourr/tgdevob/proto/s3_storageb\x06proto3"

var file_s3_storage_v1_service_proto_goTypes = []any{
	(*TempRq)(nil), // 0: mefourr.s3.storage.TempRq
	(*TempRs)(nil), // 1: mefourr.s3.storage.TempRs
}
var file_s3_storage_v1_service_proto_depIdxs = []int32{
	0, // 0: mefourr.s3.storage.S3Storage.StoreAudio:input_type -> mefourr.s3.storage.TempRq
	1, // 1: mefourr.s3.storage.S3Storage.StoreAudio:output_type -> mefourr.s3.storage.TempRs
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s3_storage_v1_service_proto_init() }
func file_s3_storage_v1_service_proto_init() {
	if File_s3_storage_v1_service_proto != nil {
		return
	}
	file_s3_storage_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s3_storage_v1_service_proto_rawDesc), len(file_s3_storage_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_s3_storage_v1_service_proto_goTypes,
		DependencyIndexes: file_s3_storage_v1_service_proto_depIdxs,
	}.Build()
	File_s3_storage_v1_service_proto = out.File
	file_s3_storage_v1_service_proto_goTypes = nil
	file_s3_storage_v1_service_proto_depIdxs = nil
}
