// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: auth/v1/message.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratorRs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratorRs) Reset() {
	*x = GeneratorRs{}
	mi := &file_auth_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratorRs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratorRs) ProtoMessage() {}

func (x *GeneratorRs) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratorRs.ProtoReflect.Descriptor instead.
func (*GeneratorRs) Descriptor() ([]byte, []int) {
	return file_auth_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratorRs) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GeneratorRs) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_auth_v1_message_proto protoreflect.FileDescriptor

const file_auth_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/message.proto\x12\fmefourr.auth\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\vGeneratorRs\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB'Z%github.com/mefourr/tgdevob/proto/authb\x06proto3"

var (
	file_auth_v1_message_proto_rawDescOnce sync.Once
	file_auth_v1_message_proto_rawDescData []byte
)

func file_auth_v1_message_proto_rawDescGZIP() []byte {
	file_auth_v1_message_proto_rawDescOnce.Do(func() {
		file_auth_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_message_proto_rawDesc), len(file_auth_v1_message_proto_rawDesc)))
	})
	return file_auth_v1_message_proto_rawDescData
}

var file_auth_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_v1_message_proto_goTypes = []any{
	(*GeneratorRs)(nil),           // 0: mefourr.auth.GeneratorRs
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_auth_v1_message_proto_depIdxs = []int32{
	1, // 0: mefourr.auth.GeneratorRs.expires_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v1_message_proto_init() }
func file_auth_v1_message_proto_init() {
	if File_auth_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_message_proto_rawDesc), len(file_auth_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_message_proto_goTypes,
		DependencyIndexes: file_auth_v1_message_proto_depIdxs,
		MessageInfos:      file_auth_v1_message_proto_msgTypes,
	}.Build()
	File_auth_v1_message_proto = out.File
	file_auth_v1_message_proto_goTypes = nil
	file_auth_v1_message_proto_depIdxs = nil
}
