// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: auth/v1/usecase.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IamTokenGenerator_GetIamToken_FullMethodName = "/mefourr.auth.IamTokenGenerator/GetIamToken"
)

// IamTokenGeneratorClient is the client API for IamTokenGenerator usecase.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IamTokenGeneratorClient interface {
	GetIamToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GeneratorRs, error)
}

type iamTokenGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIamTokenGeneratorClient(cc grpc.ClientConnInterface) IamTokenGeneratorClient {
	return &iamTokenGeneratorClient{cc}
}

func (c *iamTokenGeneratorClient) GetIamToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GeneratorRs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratorRs)
	err := c.cc.Invoke(ctx, IamTokenGenerator_GetIamToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamTokenGeneratorServer is the server API for IamTokenGenerator usecase.
// All implementations must embed UnimplementedIamTokenGeneratorServer
// for forward compatibility.
type IamTokenGeneratorServer interface {
	GetIamToken(context.Context, *emptypb.Empty) (*GeneratorRs, error)
	mustEmbedUnimplementedIamTokenGeneratorServer()
}

// UnimplementedIamTokenGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIamTokenGeneratorServer struct{}

func (UnimplementedIamTokenGeneratorServer) GetIamToken(context.Context, *emptypb.Empty) (*GeneratorRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIamToken not implemented")
}
func (UnimplementedIamTokenGeneratorServer) mustEmbedUnimplementedIamTokenGeneratorServer() {}
func (UnimplementedIamTokenGeneratorServer) testEmbeddedByValue()                           {}

// UnsafeIamTokenGeneratorServer may be embedded to opt out of forward compatibility for this usecase.
// Use of this interface is not recommended, as added methods to IamTokenGeneratorServer will
// result in compilation errors.
type UnsafeIamTokenGeneratorServer interface {
	mustEmbedUnimplementedIamTokenGeneratorServer()
}

func RegisterIamTokenGeneratorServer(s grpc.ServiceRegistrar, srv IamTokenGeneratorServer) {
	// If the following call pancis, it indicates UnimplementedIamTokenGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IamTokenGenerator_ServiceDesc, srv)
}

func _IamTokenGenerator_GetIamToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamTokenGeneratorServer).GetIamToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamTokenGenerator_GetIamToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamTokenGeneratorServer).GetIamToken(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IamTokenGenerator_ServiceDesc is the grpc.ServiceDesc for IamTokenGenerator usecase.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamTokenGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mefourr.auth.IamTokenGenerator",
	HandlerType: (*IamTokenGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIamToken",
			Handler:    _IamTokenGenerator_GetIamToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/v1/usecase.proto",
}
