// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: auth/v1/usecase.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_service_proto protoreflect.FileDescriptor

const file_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/usecase.proto\x12\fmefourr.auth\x1a\x15auth/v1/message.proto\x1a\x1bgoogle/protobuf/empty.proto2U\n" +
	"\x11IamTokenGenerator\x12@\n" +
	"\vGetIamToken\x12\x16.google.protobuf.Empty\x1a\x19.mefourr.auth.GeneratorRsB'Z%github.com/mefourr/tgdevob/proto/authb\x06proto3"

var file_auth_v1_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*GeneratorRs)(nil),   // 1: mefourr.auth.GeneratorRs
}
var file_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: mefourr.auth.IamTokenGenerator.GetIamToken:input_type -> google.protobuf.Empty
	1, // 1: mefourr.auth.IamTokenGenerator.GetIamToken:output_type -> mefourr.auth.GeneratorRs
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_service_proto_init() }
func file_auth_v1_service_proto_init() {
	if File_auth_v1_service_proto != nil {
		return
	}
	file_auth_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_proto_depIdxs,
	}.Build()
	File_auth_v1_service_proto = out.File
	file_auth_v1_service_proto_goTypes = nil
	file_auth_v1_service_proto_depIdxs = nil
}
