// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGRPCProducer creates a new instance of MockGRPCProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGRPCProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGRPCProducer {
	mock := &MockGRPCProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGRPCProducer is an autogenerated mock type for the GRPCProducer type
type MockGRPCProducer struct {
	mock.Mock
}

type MockGRPCProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGRPCProducer) EXPECT() *MockGRPCProducer_Expecter {
	return &MockGRPCProducer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockGRPCProducer
func (_mock *MockGRPCProducer) Send(ctx context.Context, duration float32) error {
	ret := _mock.Called(ctx, duration)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, float32) error); ok {
		r0 = returnFunc(ctx, duration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGRPCProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockGRPCProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - duration float32
func (_e *MockGRPCProducer_Expecter) Send(ctx interface{}, duration interface{}) *MockGRPCProducer_Send_Call {
	return &MockGRPCProducer_Send_Call{Call: _e.mock.On("Send", ctx, duration)}
}

func (_c *MockGRPCProducer_Send_Call) Run(run func(ctx context.Context, duration float32)) *MockGRPCProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 float32
		if args[1] != nil {
			arg1 = args[1].(float32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGRPCProducer_Send_Call) Return(err error) *MockGRPCProducer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGRPCProducer_Send_Call) RunAndReturn(run func(ctx context.Context, duration float32) error) *MockGRPCProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}
