// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdempotencyCheckerSvc creates a new instance of MockIdempotencyCheckerSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdempotencyCheckerSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdempotencyCheckerSvc {
	mock := &MockIdempotencyCheckerSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdempotencyCheckerSvc is an autogenerated mock type for the IdempotencyCheckerSvc type
type MockIdempotencyCheckerSvc struct {
	mock.Mock
}

type MockIdempotencyCheckerSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdempotencyCheckerSvc) EXPECT() *MockIdempotencyCheckerSvc_Expecter {
	return &MockIdempotencyCheckerSvc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockIdempotencyCheckerSvc
func (_mock *MockIdempotencyCheckerSvc) Execute(prev int, curr int) bool {
	ret := _mock.Called(prev, curr)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = returnFunc(prev, curr)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIdempotencyCheckerSvc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockIdempotencyCheckerSvc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - prev int
//   - curr int
func (_e *MockIdempotencyCheckerSvc_Expecter) Execute(prev interface{}, curr interface{}) *MockIdempotencyCheckerSvc_Execute_Call {
	return &MockIdempotencyCheckerSvc_Execute_Call{Call: _e.mock.On("Execute", prev, curr)}
}

func (_c *MockIdempotencyCheckerSvc_Execute_Call) Run(run func(prev int, curr int)) *MockIdempotencyCheckerSvc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdempotencyCheckerSvc_Execute_Call) Return(b bool) *MockIdempotencyCheckerSvc_Execute_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIdempotencyCheckerSvc_Execute_Call) RunAndReturn(run func(prev int, curr int) bool) *MockIdempotencyCheckerSvc_Execute_Call {
	_c.Call.Return(run)
	return _c
}
