// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mefourr/tgdevob/worker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRequestParserSvc creates a new instance of MockUserRequestParserSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRequestParserSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRequestParserSvc {
	mock := &MockUserRequestParserSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRequestParserSvc is an autogenerated mock type for the UserRequestParserSvc type
type MockUserRequestParserSvc struct {
	mock.Mock
}

type MockUserRequestParserSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRequestParserSvc) EXPECT() *MockUserRequestParserSvc_Expecter {
	return &MockUserRequestParserSvc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUserRequestParserSvc
func (_mock *MockUserRequestParserSvc) Execute(data []byte) (*domain.Message, error) {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*domain.Message, error)); ok {
		return returnFunc(data)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *domain.Message); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRequestParserSvc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUserRequestParserSvc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - data []byte
func (_e *MockUserRequestParserSvc_Expecter) Execute(data interface{}) *MockUserRequestParserSvc_Execute_Call {
	return &MockUserRequestParserSvc_Execute_Call{Call: _e.mock.On("Execute", data)}
}

func (_c *MockUserRequestParserSvc_Execute_Call) Run(run func(data []byte)) *MockUserRequestParserSvc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRequestParserSvc_Execute_Call) Return(message *domain.Message, err error) *MockUserRequestParserSvc_Execute_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockUserRequestParserSvc_Execute_Call) RunAndReturn(run func(data []byte) (*domain.Message, error)) *MockUserRequestParserSvc_Execute_Call {
	_c.Call.Return(run)
	return _c
}
