// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mefourr/tgdevob/worker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserCacheSaver creates a new instance of MockUserCacheSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCacheSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCacheSaver {
	mock := &MockUserCacheSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCacheSaver is an autogenerated mock type for the UserCacheSaver type
type MockUserCacheSaver struct {
	mock.Mock
}

type MockUserCacheSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCacheSaver) EXPECT() *MockUserCacheSaver_Expecter {
	return &MockUserCacheSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockUserCacheSaver
func (_mock *MockUserCacheSaver) Save(context1 context.Context, rdUser domain.RdUser) error {
	ret := _mock.Called(context1, rdUser)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RdUser) error); ok {
		r0 = returnFunc(context1, rdUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCacheSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserCacheSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - rdUser domain.RdUser
func (_e *MockUserCacheSaver_Expecter) Save(context1 interface{}, rdUser interface{}) *MockUserCacheSaver_Save_Call {
	return &MockUserCacheSaver_Save_Call{Call: _e.mock.On("Save", context1, rdUser)}
}

func (_c *MockUserCacheSaver_Save_Call) Run(run func(context1 context.Context, rdUser domain.RdUser)) *MockUserCacheSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RdUser
		if args[1] != nil {
			arg1 = args[1].(domain.RdUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCacheSaver_Save_Call) Return(err error) *MockUserCacheSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCacheSaver_Save_Call) RunAndReturn(run func(context1 context.Context, rdUser domain.RdUser) error) *MockUserCacheSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
