// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mefourr/tgdevob/worker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserFinder creates a new instance of MockUserFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFinder {
	mock := &MockUserFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserFinder is an autogenerated mock type for the UserFinder type
type MockUserFinder struct {
	mock.Mock
}

type MockUserFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFinder) EXPECT() *MockUserFinder_Expecter {
	return &MockUserFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockUserFinder
func (_mock *MockUserFinder) FindByID(context1 context.Context, s string) (domain.PgUser, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.PgUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.PgUser, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.PgUser); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(domain.PgUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserFinder_Expecter) FindByID(context1 interface{}, s interface{}) *MockUserFinder_FindByID_Call {
	return &MockUserFinder_FindByID_Call{Call: _e.mock.On("FindByID", context1, s)}
}

func (_c *MockUserFinder_FindByID_Call) Run(run func(context1 context.Context, s string)) *MockUserFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserFinder_FindByID_Call) Return(pgUser domain.PgUser, err error) *MockUserFinder_FindByID_Call {
	_c.Call.Return(pgUser, err)
	return _c
}

func (_c *MockUserFinder_FindByID_Call) RunAndReturn(run func(context1 context.Context, s string) (domain.PgUser, error)) *MockUserFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
