// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mefourr/tgdevob/worker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserCacheFinder creates a new instance of MockUserCacheFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCacheFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCacheFinder {
	mock := &MockUserCacheFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCacheFinder is an autogenerated mock type for the UserCacheFinder type
type MockUserCacheFinder struct {
	mock.Mock
}

type MockUserCacheFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCacheFinder) EXPECT() *MockUserCacheFinder_Expecter {
	return &MockUserCacheFinder_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockUserCacheFinder
func (_mock *MockUserCacheFinder) Load(context1 context.Context, s string) (domain.RdUser, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 domain.RdUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RdUser, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RdUser); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(domain.RdUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCacheFinder_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockUserCacheFinder_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserCacheFinder_Expecter) Load(context1 interface{}, s interface{}) *MockUserCacheFinder_Load_Call {
	return &MockUserCacheFinder_Load_Call{Call: _e.mock.On("Load", context1, s)}
}

func (_c *MockUserCacheFinder_Load_Call) Run(run func(context1 context.Context, s string)) *MockUserCacheFinder_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCacheFinder_Load_Call) Return(rdUser domain.RdUser, err error) *MockUserCacheFinder_Load_Call {
	_c.Call.Return(rdUser, err)
	return _c
}

func (_c *MockUserCacheFinder_Load_Call) RunAndReturn(run func(context1 context.Context, s string) (domain.RdUser, error)) *MockUserCacheFinder_Load_Call {
	_c.Call.Return(run)
	return _c
}
