// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mefourr/tgdevob/worker/internal/storage/user/cache"
	mock "github.com/stretchr/testify/mock"
	"golang.org/x/net/context"
)

// NewMockUserCache creates a new instance of MockUserCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCache {
	mock := &MockUserCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCache is an autogenerated mock type for the Store type
type MockUserCache struct {
	mock.Mock
}

type MockUserCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCache) EXPECT() *MockUserCache_Expecter {
	return &MockUserCache_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockUserCache
func (_mock *MockUserCache) Load(ctx context.Context, key string) (cache.User, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for LoadUser")
	}

	var r0 cache.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (cache.User, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) cache.User); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(cache.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCache_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadUser'
type MockUserCache_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockUserCache_Expecter) Load(ctx interface{}, key interface{}) *MockUserCache_Load_Call {
	return &MockUserCache_Load_Call{Call: _e.mock.On("LoadUser", ctx, key)}
}

func (_c *MockUserCache_Load_Call) Run(run func(ctx context.Context, key string)) *MockUserCache_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCache_Load_Call) Return(user cache.User, err error) *MockUserCache_Load_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserCache_Load_Call) RunAndReturn(run func(ctx context.Context, key string) (cache.User, error)) *MockUserCache_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserCache
func (_mock *MockUserCache) Save(ctx context.Context, user cache.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cache.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCache_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserCache_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user cache.User
func (_e *MockUserCache_Expecter) Save(ctx interface{}, user interface{}) *MockUserCache_Save_Call {
	return &MockUserCache_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *MockUserCache_Save_Call) Run(run func(ctx context.Context, user cache.User)) *MockUserCache_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cache.User
		if args[1] != nil {
			arg1 = args[1].(cache.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCache_Save_Call) Return(err error) *MockUserCache_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCache_Save_Call) RunAndReturn(run func(ctx context.Context, user cache.User) error) *MockUserCache_Save_Call {
	_c.Call.Return(run)
	return _c
}
