all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
pkgname: mocks
template: testify
packages:
  github.com/mefourr/tgdevob/worker/internal/user/usecase:
    interfaces:
      Postgres:
      Redis:
  github.com/mefourr/tgdevob/worker/internal/validator/usecase:
    interfaces:
      GRPCProducer: