all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
pkgname: mocks
template: testify
packages:
  github.com/mefourr/tgdevob/worker/internal/service:
    interfaces:
      UserCacheSaver:
      UserCacheFinder:
      UserFinder:
      IdempotencyCheckerSvc:
      UserRequestParserSvc:
      GRPCProducer:
