// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mefourr/tgdevob/worker/internal/storage/user/rediscache"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserCacheStore creates a new instance of MockUserCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCacheStore {
	mock := &MockUserCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCacheStore is an autogenerated mock type for the UserCacheStore type
type MockUserCacheStore struct {
	mock.Mock
}

type MockUserCacheStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCacheStore) EXPECT() *MockUserCacheStore_Expecter {
	return &MockUserCacheStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockUserCacheStore
func (_mock *MockUserCacheStore) Load(context1 context.Context, s string) (rediscache.User, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 rediscache.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (rediscache.User, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) rediscache.User); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(rediscache.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCacheStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockUserCacheStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserCacheStore_Expecter) Load(context1 interface{}, s interface{}) *MockUserCacheStore_Load_Call {
	return &MockUserCacheStore_Load_Call{Call: _e.mock.On("Load", context1, s)}
}

func (_c *MockUserCacheStore_Load_Call) Run(run func(context1 context.Context, s string)) *MockUserCacheStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCacheStore_Load_Call) Return(user rediscache.User, err error) *MockUserCacheStore_Load_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserCacheStore_Load_Call) RunAndReturn(run func(context1 context.Context, s string) (rediscache.User, error)) *MockUserCacheStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserCacheStore
func (_mock *MockUserCacheStore) Save(context1 context.Context, user rediscache.User) error {
	ret := _mock.Called(context1, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rediscache.User) error); ok {
		r0 = returnFunc(context1, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCacheStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserCacheStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - user rediscache.User
func (_e *MockUserCacheStore_Expecter) Save(context1 interface{}, user interface{}) *MockUserCacheStore_Save_Call {
	return &MockUserCacheStore_Save_Call{Call: _e.mock.On("Save", context1, user)}
}

func (_c *MockUserCacheStore_Save_Call) Run(run func(context1 context.Context, user rediscache.User)) *MockUserCacheStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rediscache.User
		if args[1] != nil {
			arg1 = args[1].(rediscache.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCacheStore_Save_Call) Return(err error) *MockUserCacheStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCacheStore_Save_Call) RunAndReturn(run func(context1 context.Context, user rediscache.User) error) *MockUserCacheStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
