// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mefourr/tgdevob/worker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockPostgres
func (_mock *MockPostgres) FindByID(context1 context.Context, s string) (domain.PgUser, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 domain.PgUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.PgUser, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.PgUser); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(domain.PgUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPostgres_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockPostgres_Expecter) FindByID(context1 interface{}, s interface{}) *MockPostgres_FindByID_Call {
	return &MockPostgres_FindByID_Call{Call: _e.mock.On("FindByID", context1, s)}
}

func (_c *MockPostgres_FindByID_Call) Run(run func(context1 context.Context, s string)) *MockPostgres_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_FindByID_Call) Return(pgUser domain.PgUser, err error) *MockPostgres_FindByID_Call {
	_c.Call.Return(pgUser, err)
	return _c
}

func (_c *MockPostgres_FindByID_Call) RunAndReturn(run func(context1 context.Context, s string) (domain.PgUser, error)) *MockPostgres_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
