// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mefourr/tgdevob/worker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRedis creates a new instance of MockRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedis {
	mock := &MockRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedis is an autogenerated mock type for the Redis type
type MockRedis struct {
	mock.Mock
}

type MockRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedis) EXPECT() *MockRedis_Expecter {
	return &MockRedis_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockRedis
func (_mock *MockRedis) Load(context1 context.Context, s string) (domain.RdUser, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 domain.RdUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RdUser, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RdUser); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(domain.RdUser)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedis_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockRedis_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockRedis_Expecter) Load(context1 interface{}, s interface{}) *MockRedis_Load_Call {
	return &MockRedis_Load_Call{Call: _e.mock.On("Load", context1, s)}
}

func (_c *MockRedis_Load_Call) Run(run func(context1 context.Context, s string)) *MockRedis_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_Load_Call) Return(rdUser domain.RdUser, err error) *MockRedis_Load_Call {
	_c.Call.Return(rdUser, err)
	return _c
}

func (_c *MockRedis_Load_Call) RunAndReturn(run func(context1 context.Context, s string) (domain.RdUser, error)) *MockRedis_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRedis
func (_mock *MockRedis) Save(context1 context.Context, rdUser domain.RdUser) error {
	ret := _mock.Called(context1, rdUser)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RdUser) error); ok {
		r0 = returnFunc(context1, rdUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedis_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRedis_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - rdUser domain.RdUser
func (_e *MockRedis_Expecter) Save(context1 interface{}, rdUser interface{}) *MockRedis_Save_Call {
	return &MockRedis_Save_Call{Call: _e.mock.On("Save", context1, rdUser)}
}

func (_c *MockRedis_Save_Call) Run(run func(context1 context.Context, rdUser domain.RdUser)) *MockRedis_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RdUser
		if args[1] != nil {
			arg1 = args[1].(domain.RdUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_Save_Call) Return(err error) *MockRedis_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedis_Save_Call) RunAndReturn(run func(context1 context.Context, rdUser domain.RdUser) error) *MockRedis_Save_Call {
	_c.Call.Return(run)
	return _c
}
